Jobfinder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.projects, name="projects"),
    path('project/<slug:project_slug>/', views.project, name="project"),
    path('tag/<slug:tag_slug>', views.projects_by_tag, name="tag"),
    path('create-project/', views.createProject, name="create-project"),
    path('update-project/<str:pk>', views.updateProject, name="update-project"),
    path('delete-project/<str:pk>', views.deleteProject, name="delete-project"),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.profiles, name="profiles"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerUser, name="register"),
    path('profile/<str:username>/', views.userProfile, name="user-profile"),
    path('account/', views.userAccount, name="account"),
    path('accpont-student/', views.userAccountStudent, name="accountStudent"),
    path('edit-account/', views.editAccount, name="edit-account"),
    path('create-skill/', views.createSkill, name="create-skill"),
    path('update-skill/<slug:skill_slug>/', views.updateSkill, name="update-skill"),
    path('delete-skill/<slug:skill_slug>/', views.deleteSkill, name="delete-skill"),
    path('skill/<slug:skill_slug>', views.profiles_by_skill, name="skill"),
    path('inbox/', views.inbox, name="inbox"),
    path('message/<str:pk>/', views.viewMessage, name="message"),
    path('create-message/<str:username>/', views.createMessage, name="create-message"),

]

projects/models.py
from django.db import models
from users.models import Profile, Special
import uuid
from django.utils.text import slugify

STATUS_CHOICES = ((0,"Практика"), (1,"Стажировка"), (2,"Вакансия"))

class Tag(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)


    def save(self, *args, **kwargs):
        value = self.name
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Project(models.Model):
    owner = models.ForeignKey(
        Profile, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    slug = models.SlugField(default=1)
    city = models.CharField(max_length=100, blank=True, null=False)
    kind_of_job = models.IntegerField(choices=STATUS_CHOICES, default=0)
    specialnost = models.ForeignKey(
        Special, null=True, blank=True, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True, default="project_images/default.jpg", upload_to='project_images')
    description = models.TextField(null=True, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    total_votes = models.IntegerField(default=0, null=True, blank=True)
    votes_ratio = models.IntegerField(default=0, null=True, blank=True)
    demo_link = models.CharField(max_length=500, null=True, blank=True)
    source_link = models.CharField(max_length=500, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title

    @property
    def reviewers(self):
        queryset = self.review_set.all().values_list('owner__id', flat=True)
        return queryset

    @property
    def getVoteCount(self):
        reviews = self.review_set.all()
        upVotes = reviews.filter(value='up').count()
        totalVotes = reviews.count()

        ratio = (upVotes / totalVotes) * 100
        self.vote_total = totalVotes
        self.vote_ratio = ratio

        self.save()


class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Положительная оценка'),
        ('down', 'Отрицательная оценка'),
    )
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    class Meta:
        unique_together = [['owner', 'project']]

    def __str__(self):
        return self.value

projects/forms.py
from django.forms import ModelForm
from .models import Project

class ProjectForm(ModelForm):
	class Meta:
		model = Project
		fields = ['title', 'description', 'city', 'kind_of_job', 'specialnost']
		labels = {
			'title': 'Должность',
			'description': 'Описание',
			'city': 'Город',
			'kind_of_job': 'Практика/стажировка/вакансия',
			'specialnost': 'Специальность',
		}

projects/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Project, Tag
from .forms import ProjectForm

def projects(request):
	projects = Project.objects.all()
	context = {'projects': projects}
	return render(request, 'projects/projects.html', context)

def project(request, project_slug):
	project = Project.objects.get(slug=project_slug)
	tags = project.tags.all()
	return render(request, 'projects/single-project.html', {'project': project})

def createProject(request):
	form = ProjectForm()
	if request.method == 'POST':
		form = ProjectForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('projects')
	context = {'form': form}
	return render(request, 'projects/projects_form.html', context)

def updateProject(request, pk):
	project = Project.objects.get(id=pk)
	form = ProjectForm(instance=project)
	if request.method == 'POST':
		form = ProjectForm(request.POST, instance=project)
		if form.is_valid():
			form.save()
			return redirect('projects')
	context = {'form': form}
	return render(request, 'projects/projects_form.html', context)

def deleteProject(request, pk):
	project = Project.objects.get(id=pk)
	if request.method == 'POST':
		project.delete()
		return redirect('projects')
	context = {'object': project}
	return render(request, 'delete_template.html', context)

def projects_by_tag(request, tag_slug):
    tag = get_object_or_404(Tag, slug=tag_slug)
    projects = Project.objects.filter(tags__in=[tag])
    context = {
        "projects": projects
    }

    return render(request, "projects/projects.html", context)

projects/templates/projects/projects.html
{% extends 'base.html' %}
{% block content %}

<main class="projects">
    <section class="hero-section text-center">
        <div class="container container--narrow">
            <div class="hero-section__box">
                <h2>Поиск по <span>вакансиям</span></h2>
            </div>

            <div class="hero-section__search">
                <form id='searchForm' class="form" action="{% url 'projects' %}" method="get">
                    <div class="form__field">
                        <label for="formInput#search">Поиск по специальностям </label>
                        <input class="input input--text" id="formInput#search" type="text" name="search_query"
                            placeholder="Поиск по специальностям" value="{{ search_query }}" />
                    </div>

                    <input class="btn btn--sub btn--lg" type="submit" value="Найти" />
                </form>
            </div>
        </div>
    </section>
    <section class="projectsList">
        <div class="container">
            <div class="grid grid--three">

                {% for project in projects %}
                <div class="column">
                    <div class="card project">
                        <a href="{% url 'project' project.slug %}" class="project">
{#                            <img class="project__thumbnail" src="{{ project.imageURL }}" alt="project thumbnail" />#}
                            <div class="card__body">
                                <h3 class="project__title">{{ project.title }}</h3>

                                <p><a class="project__author" href="#">Компания:
                                        {{ project.owner.name }}</a>
                                </p>
                                <p class="project--rating">
                                    <span style="font-weight: bold;">Тип:</span>  {{ project.get_kind_of_job_display }}
                                </p>
                                <p class="project--rating">
                                    <span style="font-weight: bold;">Город:</span>  {{ project.city }}
                                </p>
{#                                 <p class="project--rating">#}
{#                                    <span style="font-weight: bold;">всего отзывов:</span> {{ project.total_votes }}#}
{#                                </p>#}
                                <div class="project__tags">
                                    {% for tag in project.tags.all %}
                                    <a href="{% url 'tag' tag.slug %}" class="tag tag--pill tag--main">{{tag}}</a>

                                    {% endfor %}

                                </div>
                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </section>
</main>

{% endblock %}

projects/templates/projects/projects_form.html
{% extends 'base.html' %}
{% block content %}

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i></a>
            <br>

            <form class="form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {% for field in form %}
                <div class="form__field">
                    <label for="formInput#text">{{ field.label }}</label>
                    {{ field }}
                </div>
                {% endfor %}

                <div class="form__field">
                    {% for tag in project.tags.all %}
                    <div class="project-tag tag tag--pill tag--main" data-tag="{{tag.id}}"
                        data-project="{{project.id}}">{{ tag.name }} &#215;</div>
                    {% endfor %}
                </div>

{#                <div class="form__field">#}
{#                    <label for="formInput#text">Теги</label>#}
{#                    <textarea class="input" name="newtags" placeholder="Добавьте теги"></textarea>#}
{#                </div>#}
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Сохранить" />
            </form>
        </div>
    </div>
</main>

{% endblock %}

projects/templates/projects/single-project.html
{% extends 'base.html' %}

{% block content %}

<main class="singleProject my-md">
    <div class="container">
        <div class="layout">
{#            <div class="column column--1of3">#}
{#                <h3 class="singleProject__subtitle">Платформа и стек</h3>#}
{#                <div class="singleProject__toolStack">#}
{#                {% for tag in project.tags.all %}#}
{#                <a href="{% url 'tag' tag.slug %}" class="tag tag--pill tag--sub tag--lg">{{tag}}</a>#}
{#                {% endfor %}#}
{#                </div>#}
{##}
{#                {% if project.source_link %}#}
{#                <a class="singleProject__liveLink" href="{{ project.source_link }}" target="_blank"><i#}
{#                        class="im im-external-link"></i>Исходный код на GitHub#}
{#                </a>#}
{#                {% endif %}#}
{##}
{#                {% if project.demo_link %}#}
{#                <a class="singleProject__liveLink" href="{{ project.source_link }}" target="_blank"><i#}
{#                        class="im im-external-link"></i>Демо-сайт#}
{##}
{#                </a>#}
{#                {% endif %}#}

            </div>
            <div class="column column--2of3">
{#                <img class="singleProject__preview" src="{{ project.imageURL }}" alt="portfolio thumbnail" />#}
                <a href="#"
                    class="singleProject__developer">{{ project.owner.name }}</a>
                <h2 class="singleProject__title">{{ project.title }}</h2>
                <h3 class="singleProject__subtitle">Информация о вакансии</h3>
                <h3 class="singleProject__subtitle">{{ project.city }}</h3>
                <h3 class="singleProject__subtitle">{{ project.get_kind_of_job_display }}</h3>
                <div class="singleProject__info">
                    {{ project.description }}
                </div>
                <div class="comments">
{#                    <h3 class="singleProject__subtitle">Оценки и отзывы</h3>#}
{#                    <h5 class="project--rating">#}
{#                    процент положительных отзывов: {{project.votes_ratio}}#}
{#                    </h5>#}
{#                    <h5 class="project--rating">#}
{#                    всего отзывов: {{project.total_votes}}#}
{#                    </h5>#}
{#                    {% if request.user.profile.id in project.reviewers %}#}
{#                    <p>Вы уже писали отзыв об этом проекте</p>#}
{##}
{#                    {% elif request.user.profile == project.owner %}#}
{#                    <p>Вы не можете оставлять отзывы к собственным проектам</p>#}

{#                    {% elif request.user.is_authenticated %}#}
                    <form class="form" action="{% url 'project' project.id %}" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form__field">
                            <label for="formInput#textarea">{{ field.label }}</label>
                            {{field}}
                        </div>
                        {% endfor %}
                        <input class="btn btn--sub btn--lg" type="submit" value="Оставить отклик" />
                    </form>
{#                    {% else %}#}
{#                    <a href="{% url 'login' %}?next={{ request.path }}">Войдите, чтобы оставить отзыв</a>#}
{#                    {% endif %}#}

{#                    <div class="commentList">#}
{#                        {% for review in project.review_set.all %}#}
{#                        {% if review.body %}#}
{#                        <div class="comment">#}
{#                            <a href="{% url 'user-profile' review.owner.id  %}">#}
{#                                <img class="avatar avatar--md" src="{{ review.owner.profile_image.url }}" alt="user" />#}
{#                            </a>#}
{##}
{##}
{#                            <div class="comment__details">#}
{#                                <a href="{% url 'user-profile' review.owner.id  %}"#}
{#                                    class="comment__author">{{ review.owner.name }}</a>#}
{#                                <p class="comment__info">{{ review.body|linebreaksbr }}</p>#}
{#                            </div>#}
{##}
{#                        </div>#}
{#                        {% endif %}#}
{#                        {% endfor %}#}
{##}
{#                    </div>#}
                </div>
            </div>
        </div>
    </div>
    </div>
</main>

{% endblock %}